spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /api

# spring security相关的要放行不拦截的url
permits: /,/pub/**,/test*,/login,/message*,/ws,/app/**,/queue/**,/topic/**,/ws/**
